baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Mind of Marvin'
theme = "PaperMod"

# Enable search
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

# Enable menu
[menu]
main = [
    {identifier = "posts", name = "Posts", url = "/posts/", weight = 10},
    {identifier = "about", name = "About", url = "/about/", weight = 20}
]

# Enable post list view
[params.homeInfoParams]
Title = "Welcome to my blog"
Content = "A place for my thoughts and experiences"

[params.cover]
linkFullImages = true

[params.listView]
enable = true
showSummary = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = "Welcome to my personal blog where I share my thoughts and experiences"
author = "Marvin Vilaysack"
# defaultTheme: light, dark, auto
defaultTheme = "auto"

[params.profileMode]
enabled = true
title = "Hi there! ðŸ‘‹"
subtitle = "This is my personal corner of the internet where I share my thoughts and experiences"
imageUrl = ""
imageTitle = "my photo"

[[params.profileMode.buttons]]
name = "Blog"
url = "posts"

[[params.profileMode.buttons]]
name = "About"
url = "about"

[[params.socialIcons]]
name = "github"
url = "https://github.com/marvintv"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/marvintv"
